"""Streamlit dashboard for real-time match analytics.

The dashboard reads only the consolidated parquet files produced by
`streaming_pipeline.py`:
- `output/processed/events.parquet`
- `output/aggregates/team_metrics.parquet`
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st
from settings import (
    EVENTS_FILE,
    INCREMENTAL_SEGMENTS_FILE,
    METRICS_FILE,
    REPORT_PDF_FILE,
    REPORT_WINDOW_MINUTES,
    WINDOW_METRICS_FILE,
)

try:
    from streamlit_autorefresh import st_autorefresh

    AUTOREFRESH_AVAILABLE = True
except ImportError:
    AUTOREFRESH_AVAILABLE = False


PROJECT_ROOT = Path(__file__).resolve().parent.parent

EVENT_COLUMNS = [
    "event_id",
    "timestamp",
    "match_id",
    "team",
    "player",
    "event_type",
    "zone",
    "minute",
    "value",
    "period",
    "snapshot_time",
    "batch_id",
]

METRIC_COLUMNS = [
    "team",
    "total_events",
    "goals",
    "shots",
    "passes",
    "fouls",
    "recoveries",
    "avg_value",
    "snapshot_time",
    "batch_id",
    "snapshot_event_count",
]

SEGMENT_COLUMNS = [
    "segment_id",
    "match_id",
    "window_start_minute",
    "window_end_minute",
    "window_minutes",
    "text",
    "metrics_json",
    "rag_context",
    "llm_model",
    "trace_json",
    "generated_at",
]


def _empty_events_df() -> pd.DataFrame:
    """Return an empty events dataframe with the expected schema."""
    return pd.DataFrame(columns=EVENT_COLUMNS)


def _empty_metrics_df() -> pd.DataFrame:
    """Return an empty metrics dataframe with the expected schema."""
    return pd.DataFrame(columns=METRIC_COLUMNS)


def _read_parquet_file(path: Path, columns: list[str]) -> pd.DataFrame:
    """Read one consolidated parquet file, returning an empty typed frame on failure."""
    if not path.exists() or not path.is_file():
        return pd.DataFrame(columns=columns)

    try:
        df = pd.read_parquet(path)
    except Exception as exc:
        st.warning(f"No se pudo leer {path.name}: {exc}")
        return pd.DataFrame(columns=columns)

    for column in columns:
        if column not in df.columns:
            df[column] = None
    return df[columns]


def load_incremental_segments() -> pd.DataFrame:
    """Load report segments already generated by the streaming pipeline."""
    df = _read_parquet_file(INCREMENTAL_SEGMENTS_FILE, SEGMENT_COLUMNS)
    if df.empty:
        return pd.DataFrame(columns=SEGMENT_COLUMNS)

    df["window_start_minute"] = pd.to_numeric(df["window_start_minute"], errors="coerce").fillna(0).astype(int)
    df["window_end_minute"] = pd.to_numeric(df["window_end_minute"], errors="coerce").fillna(0).astype(int)
    df["window_minutes"] = pd.to_numeric(df["window_minutes"], errors="coerce").fillna(REPORT_WINDOW_MINUTES).astype(int)
    df["generated_at"] = pd.to_datetime(df["generated_at"], errors="coerce")
    return df.sort_values(["match_id", "window_start_minute"])


def load_window_metrics() -> pd.DataFrame:
    """Load window metrics already generated by the streaming pipeline."""
    if not WINDOW_METRICS_FILE.exists() or not WINDOW_METRICS_FILE.is_file():
        return pd.DataFrame()

    try:
        df = pd.read_parquet(WINDOW_METRICS_FILE)
    except Exception as exc:
        st.warning(f"No se pudo leer {WINDOW_METRICS_FILE.name}: {exc}")
        return pd.DataFrame()

    for column in ["window_start_minute", "window_end_minute", "events", "shots", "goals", "passes", "fouls", "recoveries"]:
        if column in df.columns:
            df[column] = pd.to_numeric(df[column], errors="coerce").fillna(0).astype(int)
    return df.sort_values(["window_start_minute", "team"])


def load_processed_events() -> pd.DataFrame:
    """Load processed events from the single consolidated parquet file."""
    df = _read_parquet_file(EVENTS_FILE, EVENT_COLUMNS)
    if df.empty:
        return _empty_events_df()

    df["minute"] = pd.to_numeric(df["minute"], errors="coerce").fillna(0).astype(int)
    df["value"] = pd.to_numeric(df["value"], errors="coerce").fillna(0).astype(int)
    df["period"] = pd.to_numeric(df["period"], errors="coerce").fillna(0).astype(int)
    df["snapshot_time"] = pd.to_datetime(df["snapshot_time"], errors="coerce")
    return df


def load_team_metrics() -> pd.DataFrame:
    """Load team metric snapshots from the single consolidated parquet file."""
    df = _read_parquet_file(METRICS_FILE, METRIC_COLUMNS)
    if df.empty:
        return _empty_metrics_df()

    numeric_cols = [
        "total_events",
        "goals",
        "shots",
        "passes",
        "fouls",
        "recoveries",
        "avg_value",
        "batch_id",
        "snapshot_event_count",
    ]
    for column in numeric_cols:
        df[column] = pd.to_numeric(df[column], errors="coerce").fillna(0)

    count_cols = [col for col in numeric_cols if col != "avg_value"]
    df[count_cols] = df[count_cols].astype(int)
    df["snapshot_time"] = pd.to_datetime(df["snapshot_time"], errors="coerce")
    return df


def latest_team_snapshot(metrics_df: pd.DataFrame) -> pd.DataFrame:
    """Return the latest cumulative metrics row for each team."""
    if metrics_df.empty:
        return _empty_metrics_df()

    return (
        metrics_df.sort_values(["snapshot_time", "batch_id"])
        .groupby("team", as_index=False)
        .tail(1)
        .sort_values("team")
    )


def render_empty_state() -> None:
    """Render a concise message while Spark has not produced parquet files yet."""
    st.info(
        "Aun no hay datos consolidados. Arranca Kafka, el productor y "
        "`python src/streaming_pipeline.py`; Streamlit se actualizara cada 30 segundos."
    )


def render_live_events_tab(events_df: pd.DataFrame) -> None:
    """Render live events table, key metrics, and event-type chart."""
    st.subheader("Eventos")
    if events_df.empty:
        render_empty_state()
        return

    display_cols = ["minute", "team", "player", "event_type", "zone", "value", "snapshot_time"]
    display_df = events_df[display_cols].tail(25).sort_values(by="minute", ascending=False)
    st.dataframe(display_df, use_container_width=True, hide_index=True)

    event_type = events_df["event_type"].astype(str).str.lower()
    total_events = len(events_df)
    total_goals = int(((event_type == "goal") | ((event_type == "shot") & (events_df["value"] == 3))).sum())
    total_shots = int((event_type == "shot").sum())
    total_fouls = int(event_type.isin(["foul committed", "foul won"]).sum())

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Eventos", total_events)
    m2.metric("Goles", total_goals)
    m3.metric("Tiros", total_shots)
    m4.metric("Faltas", total_fouls)

    st.subheader("Distribucion por tipo de evento")
    event_counts = events_df["event_type"].value_counts().sort_values(ascending=False)
    st.bar_chart(event_counts)


def render_team_metrics_tab(metrics_df: pd.DataFrame) -> None:
    """Render latest team comparison and metric history."""
    st.subheader("Metricas acumuladas por equipo")
    if metrics_df.empty:
        render_empty_state()
        return

    latest_df = latest_team_snapshot(metrics_df)
    display_cols = [
        "team",
        "total_events",
        "goals",
        "shots",
        "passes",
        "fouls",
        "recoveries",
        "avg_value",
        "snapshot_time",
    ]
    st.dataframe(latest_df[display_cols], use_container_width=True, hide_index=True)

    chart_df = metrics_df.dropna(subset=["snapshot_time"]).copy()
    if not chart_df.empty:
        st.subheader("Evolucion de eventos acumulados")
        pivot_df = chart_df.pivot_table(
            index="snapshot_time",
            columns="team",
            values="total_events",
            aggfunc="last",
        ).sort_index()
        st.line_chart(pivot_df)

    teams = latest_df.head(2).to_dict(orient="records")
    if teams:
        cols = st.columns(len(teams))
        for column, team in zip(cols, teams):
            with column:
                st.markdown(f"### {team['team']}")
                st.metric("Eventos", int(team["total_events"]))
                st.metric("Goles", int(team["goals"]))
                st.metric("Tiros", int(team["shots"]))
                st.metric("Pases", int(team["passes"]))


def render_incremental_report_tab(events_df: pd.DataFrame) -> None:
    """Render incremental report segments generated by the streaming pipeline."""
    st.subheader(f"Informe incremental cada {REPORT_WINDOW_MINUTES} minutos")
    if events_df.empty:
        render_empty_state()
        return

    segments_df = load_incremental_segments()
    window_metrics_df = load_window_metrics()
    if not window_metrics_df.empty:
        chart_df = (
            window_metrics_df.groupby("window_start_minute", as_index=False)
            .agg(
                eventos=("events", "sum"),
                tiros=("shots", "sum"),
                goles=("goals", "sum"),
                recuperaciones=("recoveries", "sum"),
            )
            .sort_values("window_start_minute")
            .set_index("window_start_minute")
        )
        st.subheader("Actividad por ventana")
        st.line_chart(chart_df)

    if segments_df.empty:
        st.info(
            "Todavia no hay ventanas completas para narrar. "
            f"El pipeline de streaming generara texto cuando exista al menos una ventana cerrada de {REPORT_WINDOW_MINUTES} minutos."
        )
        return

    for row in segments_df.itertuples(index=False):
        title = f"Minutos {int(row.window_start_minute)}-{int(row.window_end_minute)}"
        with st.expander(title, expanded=True):
            st.write(row.text)
            st.caption(f"Modelo: {row.llm_model or 'no disponible'} | Generado: {row.generated_at}")
            with st.popover("Trazabilidad"):
                try:
                    trace = json.loads(row.trace_json) if row.trace_json else []
                except Exception:
                    trace = []
                for step in trace:
                    st.write(f"- {step}")
            with st.popover("RAG y metricas"):
                st.code(row.rag_context or "Sin contexto RAG", language="text")
                st.code(row.metrics_json or "{}", language="json")


def render_export_tab(events_df: pd.DataFrame, metrics_df: pd.DataFrame) -> None:
    """Render the PDF generated by the streaming pipeline."""
    st.subheader("Informe automatico PDF")

    disabled = events_df.empty and metrics_df.empty
    if disabled:
        render_empty_state()
        return

    if not REPORT_PDF_FILE.exists() or not REPORT_PDF_FILE.is_file():
        st.info("El pipeline de streaming aun no ha generado el PDF.")
        return

    st.success("Informe PDF generado por el pipeline de streaming.")
    st.download_button(
        "Descargar informe PDF",
        data=REPORT_PDF_FILE.read_bytes(),
        file_name="match_report.pdf",
        mime="application/pdf",
    )


def render_pipeline_status_tab() -> None:
    """Render output readiness and configuration details."""
    events_ready = EVENTS_FILE.exists() and EVENTS_FILE.is_file()
    metrics_ready = METRICS_FILE.exists() and METRICS_FILE.is_file()
    window_metrics_ready = WINDOW_METRICS_FILE.exists() and WINDOW_METRICS_FILE.is_file()
    segments_ready = INCREMENTAL_SEGMENTS_FILE.exists() and INCREMENTAL_SEGMENTS_FILE.is_file()
    pdf_ready = REPORT_PDF_FILE.exists() and REPORT_PDF_FILE.is_file()

    st.subheader("Estado")
    st.write(f"Eventos consolidados: {'OK' if events_ready else 'pendiente'}")
    st.write(f"Metricas consolidadas: {'OK' if metrics_ready else 'pendiente'}")
    st.write(f"Metricas por ventana: {'OK' if window_metrics_ready else 'pendiente'}")
    st.write(f"Segmentos incrementales: {'OK' if segments_ready else 'pendiente'}")
    st.write(f"PDF automatico: {'OK' if pdf_ready else 'pendiente'}")
    st.write(f"Tamano de ventana configurado: {REPORT_WINDOW_MINUTES} minutos")

    st.subheader("Ficheros leidos por Streamlit")
    st.code(
        f"{EVENTS_FILE}\n{METRICS_FILE}\n{WINDOW_METRICS_FILE}\n{INCREMENTAL_SEGMENTS_FILE}\n{REPORT_PDF_FILE}",
        language="text",
    )

    if st.button("Actualizar ahora"):
        st.rerun()


def main() -> None:
    """Main Streamlit entrypoint."""
    st.set_page_config(page_title="Real-Time Match Analytics Dashboard", page_icon=":soccer:", layout="wide")
    st.title("Real-Time Match Analytics Dashboard")

    if AUTOREFRESH_AVAILABLE:
        st_autorefresh(interval=30_000, key="dashboard_autorefresh")
    else:
        st.caption("Auto-refresh no disponible. Usa el boton de estado para actualizar.")

    events_df = load_processed_events()
    metrics_df = load_team_metrics()

    tab_live, tab_team, tab_incremental, tab_export, tab_status = st.tabs(
        ["Eventos", "Metricas por equipo", "Informe incremental", "Exportar informe", "Estado"]
    )

    with tab_live:
        render_live_events_tab(events_df)

    with tab_team:
        render_team_metrics_tab(metrics_df)

    with tab_incremental:
        render_incremental_report_tab(events_df)

    with tab_export:
        render_export_tab(events_df, metrics_df)

    with tab_status:
        render_pipeline_status_tab()


if __name__ == "__main__":
    main()
